name: Deploy web

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yaml
    with:
      IMAGE_NAME: ghcr.io/triple-c-group/web:latest
      DOCKERFILE_PATH: apps/web/Dockerfile
    secrets: inherit
