name: Build, Publish and Deploy Template

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        type: string
        required: true
      DOCKERFILE_PATH:
        type: string
        required: true

jobs:
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        if: ${{ inputs.DOCKERFILE_PATH == 'apps/api/Dockerfile' }}
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Build with Maven
        if: ${{ inputs.DOCKERFILE_PATH == 'apps/api/Dockerfile' }}
        run: cd apps/api && mvn clean package -DskipTests

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.DOCKERFILE_PATH }}
          push: true
          tags: ${{ inputs.IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
