name: Deploy api

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/api/**"

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    needs: build
    uses: ./.github/workflows/deploy-template.yaml
    with:
      IMAGE_NAME: ghcr.io/triple-c-group/api:latest
      DOCKERFILE_PATH: apps/api/Dockerfile
    secrets: inherit
