name: Deploy recommendation engine

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/recommendation-engine/**"

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yaml
    with:
      IMAGE_NAME: ghcr.io/triple-c-group/recommendation-engine:latest
      DOCKERFILE_PATH: apps/recommendation-engine/Dockerfile
    secrets: inherit
